=== vikagetmanskaya/Task2/src/main/resources/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:plant" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="plant" abstract="true" type="tns:PlantType"/>
    <element name="tree" type="tns:TreeType" substitutionGroup="tns:plant"/>
    <element name="flower" type="tns:FlowerType" substitutionGroup="tns:plant"/>
    <element name="bush" type="tns:BushType" substitutionGroup="tns:plant"/>
    <complexType name="PlantType">
        <sequence>
            <element name="soil" type="tns:SoilType"/>
            <element name="origin" type="string"/>
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="multiplying" type="tns:Multiplying"/>
            <element name="date-of-planting" type="date"/>
            <element name="growing-tips" type="tns:GrowingTips"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" use="required"/>
    </complexType>
    <simpleType name="SoilType">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="ground"/>
            <enumeration value="sod-podzolic"/>
        </restriction>
    </simpleType>
    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaves"/>
            <enumeration value="cuttings"/>
            <enumeration value="seeds"/>
        </restriction>
    </simpleType>
    <complexType name="VisualParameters">
        <sequence>
            <element name="stem-color" type="string"/>
            <element name="leaf-color" type="string"/>
            <element name="size" type="tns:Size"/>
        </sequence>

    </complexType>
    <simpleType name="Size">

        <restriction base="string">

            <pattern value="\d+?\.\s[m]"/>
        </restriction>


    </simpleType>
    <complexType name="GrowingTips">
        <sequence>
            <element name="temperature" type="tns:Temperature"/>
            <element name="lighting" type="tns:Lighting"/>
            <element name="watering" type="tns:Watering"/>
        </sequence>
    </complexType>
    <simpleType name="Temperature">
        <restriction base="string">
            <pattern value="\d+?\.\sdegree"/>
        </restriction>
    </simpleType>
    <simpleType name="Lighting">
        <restriction base="string">
            <enumeration value="light-loving"/>
            <enumeration value="not-light-loving"/>
        </restriction>
    </simpleType>
    <simpleType name="Watering">
        <restriction base="string">
            <pattern value="\d+\s ml"/>
        </restriction>
    </simpleType>
    <complexType name="TreeType">

        <complexContent>
            <extension base="tns:PlantType">
                <attribute name="max-age" type="int" use="optional"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="FlowerType">

        <complexContent>
            <extension base="tns:PlantType">
                <attribute name="type-of-flower" use="optional">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="field"/>
                                <enumeration value="decorative"/>
                            </restriction>
                        </simpleType>
                </attribute>

            </extension>
        </complexContent>
    </complexType>

    <complexType name="BushType">

        <complexContent>
            <extension base="tns:PlantType">
                <attribute name="amount-of-trunks" type="int" use="optional"/>
            </extension>
        </complexContent>

    </complexType>
</schema>

=== vikagetmanskaya/Task2/src/test/resources/data/flowers1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <flower id="a1" name="chamomile" type-of-flower="field">
        <soil>ground</soil>
        <origin>Altai</origin>
        <visual-parameters>
            <steam-color>green</steam-color>
            <leaf-color>white</leaf-color>
            <size>0.2 m</size>
        </visual-parameters>
        <multiplying>seeds</multiplying>
        <date-of-planting>2021-05-15</date-of-planting>
        <growing-tips>
            <temperature>20 degree</temperature>
            <lightning>light-loving</lightning>
            <watering>200 ml</watering>
        </growing-tips>
    </flower>
    <tree id="a2" name="eucalyptus" max-age = "100">
        <soil>ground</soil>
        <origin>Australia</origin>
        <visual-parameters>
            <steam-color>brown</steam-color>
            <leaf-color>green</leaf-color>
            <size>30 m</size>
        </visual-parameters>
        <multiplying>cutting</multiplying>
        <date-of-planting>2021-03-20</date-of-planting>
        <growing-tips>
            <temperature>15 degree</temperature>
            <lightning>light-loving</lightning>
            <watering>1000000 ml</watering>
        </growing-tips>
    </tree>
    <bush id="a3" name="jasmine" amount-of-trunks ="10">
        <soil>sod-podzolic</soil>
        <origin>Arabia</origin>
        <visual-parameters>
            <steam-color>green</steam-color>
            <leaf-color>green</leaf-color>
            <size>3 m</size>
        </visual-parameters>
        <multiplying>cutting</multiplying>
        <date-of-planting>2021-10-01</date-of-planting>
        <growing-tips>
            <temperature>23 degree</temperature>
            <lightning>not-light-loving</lightning>
            <watering>10000 ml</watering>
        </growing-tips>
    </bush>
</flowers>

=== vikagetmanskaya/Task2/src/test/resources/data/flowers2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <flower name="" type-of-flower = "field"
        <soil>ground</soil>
        <origin>Altai</origin>
        <visual-parameters>
            <leaf-color>white</leaf-color>
            <steam-color>green</steam-color>
            <size>0.2 m</size>
        </visual-parameters>
        <multiplying>seeds</multiplying>
        <date-of-planting>2021-05-15</date-of-planting>
        <growing-tips>
            <temperature>20 degree</temperature>
            <lightning>light-loving</lightning>
            <watering>1000 ml</watering>
        </growing-tips>
    </flower>
    <tree id="a2" name="eucalyptus" max-age = "100">
        <soil>ground</soil>
        <origin>Australia</origin>
        <visual-parameters>
            <steam-color>brown</steam-color>
            <leaf-color>green</leaf-color>
            <size>30 m</size>
        </visual-parameters>
        <multiplying>cutting</multiplying>
        <date-of-planting>2021-03-20</date-of-planting>
        <growing-tips>
            <temperature>15 degree</temperature>
            <lightning>light-loving</lightning>
            <watering>1000000 ml</watering>
        </growing-tips>
    </tree>
</flowers>
