=== vikagetmanskaya/Task2/files/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:plant" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="plant" abstract="true"/>
    <element name="tree" type="tns:Tree" substitutionGroup="tns:plant"/>
    <element name="flower" type="tns:Flower" substitutionGroup="tns:plant"/>
    <element name="bush" type="tns:Bush" substitutionGroup="tns:plant"/>
    <simpleType name="SoilType">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="ground"/>
            <enumeration value="sod-podzolic"/>
        </restriction>
    </simpleType>
    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaves"/>
            <enumeration value="cuttings"/>
            <enumeration value="seeds"/>
        </restriction>
    </simpleType>
    <complexType name="VisualParameters">
        <sequence>
            <element name="stem-color" type="string"/>
            <element name="leaf-color" type="string"/>
            <element name="size" type="tns:Size"/>
        </sequence>

    </complexType>
    <simpleType name="Size">

        <restriction base="string">

            <pattern value="\d+?\.\s[m]"/>
        </restriction>


    </simpleType>
    <complexType name="GrowingTips">
        <sequence>
            <element name="temperature" type="tns:Temperature"/>
            <element name="lighting" type="tns:Lighting"/>
            <element name="watering" type="tns:Watering"/>
        </sequence>
    </complexType>
    <simpleType name="Temperature">
        <restriction base="string">
            <pattern value="\d+?\.\sdegree"/>
        </restriction>
    </simpleType>
    <simpleType name="Lighting">
        <restriction base="string">
            <enumeration value="light-loving"/>
            <enumeration value="not-light-loving"/>
        </restriction>
    </simpleType>
    <simpleType name="Watering">
        <restriction base="string">
            <pattern value="\d+\s ml"/>
        </restriction>
    </simpleType>
    <complexType name="Tree">

        <sequence>
            <element name="soil" type="tns:SoilType"/>
            <element name="origin" type="string"/>
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="multiplying" type="tns:Multiplying"/>
            <element name="date-of-planting" type="date"/>
            <element name="growing-tips" type="tns:GrowingTips"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="description" type="string" use="optional"/>
    </complexType>
    <complexType name="Flower">

        <sequence>
            <element name="soil" type="tns:SoilType"/>
            <element name="origin" type="string"/>
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="multiplying" type="tns:Multiplying"/>
            <element name="date-of-planting" type="date"/>
            <element name="growing-tips" type="tns:GrowingTips"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="description" type="string" use="optional"/>
    </complexType>

    <complexType name="Bush">

        <sequence>
            <element name="soil" type="tns:SoilType"/>
            <element name="origin" type="string"/>
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="multiplying" type="tns:Multiplying"/>
            <element name="date-of-planting" type="date"/>
            <element name="growing-tips" type="tns:GrowingTips"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="description" type="string" use="optional"/>

    </complexType>
</schema>

=== vikagetmanskaya/Task2/files/flowers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <flower id="1" name="chamomile">
        <soil>ground</soil>
        <origin>Altai</origin>
        <visual-parametrs>
            <steam-color>green</steam-color>
            <leaf-color>white</leaf-color>
            <size>0.2 m</size>
        </visual-parametrs>
        <multiplying>seeds</multiplying>
        <date-of-planting>2021-05-15</date-of-planting>
        <growing-tips>
            <temperature>20 degree</temperature>
            <lighting>light-loving</lighting>
            <watering>200 ml</watering>
        </growing-tips>
    </flower>
    <tree id="2" name="eucalyptus" description="evergreen tree">
        <soil>ground</soil>
        <origin>Australia</origin>
        <visual-parametrs>
            <steam-color>brown</steam-color>
            <leaf-color>green</leaf-color>
            <size>30 m</size>
        </visual-parametrs>
        <multiplying>cuttings</multiplying>
        <date-of-planting>2021-03-20</date-of-planting>
        <growing-tips>
            <temperature>15 degree</temperature>
            <lighting>light-loving</lighting>
            <watering>1000000 ml</watering>
        </growing-tips>
    </tree>
    <bush id="3" name="jasmine">
        <soil>sod-podzolic</soil>
        <origin>Arabia</origin>
        <visual-parametrs>
            <steam-color>green</steam-color>
            <leaf-color>green</leaf-color>
            <size>3 m</size>
        </visual-parametrs>
        <multiplying>cuttings</multiplying>
        <date-of-planting>2021-10-01</date-of-planting>
        <growing-tips>
            <temperature>23 degree</temperature>
            <lighting>not-light-loving</lighting>
            <watering>10000 ml</watering>
        </growing-tips>
    </bush>
</flowers>
